### ISSUE TITLE
Peer to peer code review - 23rd Aug

### ISSUE THREAD

**Issue by MaiRizk** [MaiRizk/my-portfolio#3]

**Comment by SelmaNdapanda** [comment]
I suggest you need to revisit your headline section styling, as there is too much space left at the bottom of your project compared to the Figma design.

**Comment by AhmedNazirMusah** [comment]
https://github.com/MaiRizk/my-portfolio/blob/165e48a2cb7fdcbbf107abeb390375e754feada6/styles.css#L39-L46

Neatly done I wanted to implement the background-image styling but I really struggled with the process.
Very good.

**Comment by adel-gu** [comment]
**Hi @MaiRizk 👋** 
#### The menu is a clickable area for the user: 

- [ ] so for that and for good semantics practices I suggest wrapping this `img` element inside a `button` tag 

https://github.com/MaiRizk/my-portfolio/blob/83a281a50fd0d34de894721036b85eb3d84dd4a3/index.html#L26
